services:
  bap-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bap-protocol-webserver
    depends_on:
      - rabbitmq
    environment:
      ENV: prod
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      MONGO_DATABASE_URL: mongodb://3.7.149.46:27017/
      BAP_URL: http://localhost:5555
      CLIENT_WEBHOOK_ENDPOINT: http://localhost:5555/webhook
      BAP_PRIVATE_KEY: e9EcgQ4Y63bEu3g2pRERyumsqdMbHtSfr6yqWMek0osMI8+x39jm2xFWI5ksosc0RHIyVBJequg6fDTh+K/fFA==
      BAP_UNIQUE_KEY_ID: afd07d7c-44b0-4fd7-a700-f4a4eea3b03b
      BAP_PUBLIC_KEY: DCPPsd/Y5tsRViOZLKLHNERyMlQSXqroOnw04fiv3xQ=
      BAP_ID: staging-api.klynk.dev
      VERIFICATION_ENABLE: "True"
      FLASK_SERVER: "True"
      QUEUE_ENABLE: "False"
      ELASTIC_SEARCH_QUEUE_ENABLE: "False"
    expose:
      - 5555
    ports:
      - 5555:5555
    networks:
      - ondc-network

  bap-consumer:
    build:
      context: .
      dockerfile: dockerfile-consumer
    container_name: bap-protocol-consumer
    depends_on:
      - rabbitmq
    environment:
      ENV: prod
      MONGO_DATABASE_URL: mongodb://3.7.149.46:27017/
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      BAP_PRIVATE_KEY: e9EcgQ4Y63bEu3g2pRERyumsqdMbHtSfr6yqWMek0osMI8+x39jm2xFWI5ksosc0RHIyVBJequg6fDTh+K/fFA==
      BAP_UNIQUE_KEY_ID: afd07d7c-44b0-4fd7-a700-f4a4eea3b03b
      BAP_PUBLIC_KEY: DCPPsd/Y5tsRViOZLKLHNERyMlQSXqroOnw04fiv3xQ=
      BAP_ID: staging-api.klynk.dev
      FLASK_SERVER: "False"
    networks:
      - ondc-network

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - ondc-network

networks:
  ondc-network:
    driver: bridge
